application_content:
  application_text:
    application_questions:
      welcome_text:
        text:
          "Welcome to the discharge monitoring application. We're going to ask some
          personal questions. Is now a good time?"
        response_type:
          "Bool"
      user_identification:
        text:
          "I wanted to confirm that this was Jon. Is this correct?"
        response_type:
          "Bool"
      user_2nd_step_identification:
        text:
          "Could you confirm your birthdate"
        response_type:
          "DATE_ANSWER"
    application_statements:
      failed_user_confirmation:
        "Hmm... something went wrong."
      exit_message:
        "Thank you for your input Jon. We'll be sending this information to your surgeon,
        who will follow-up with you if any additional information is required or if he needs
        to see you sooner than your scheduled appointment."
  clinical_questions:
      mobility:
        text:
          ["Have you been able to walk around today?"]
        response_type:
          "Bool"
      pain_calves:
        text:
          ["Are you experiencing any pain or swelling in your cavles"]
        response_type:
          "Bool"
      food_eat:
        text:
          ["Have you been able to eat any meals?"]
        response_type:
          "Bool"
      drink_liquids:
        text:
          ["Have you been drinking liquids?"]
        response_type:
          "Bool"
      pain_change:
        text:
          ["Is your pain increased since yesterday?"]
        response_type:
          "Bool"
      urinating_regularly:
        text:
          ["Are you urinating regularly?"]
        response_type:
          "Bool"
      bowel_movement:
        text:
          ["Were you able to have a bowel movement today?"]
        response_type:
          "Bool"
      condition_change:
        text:
          ["Overall, do you feel better, worse or about the same as you did yesterday?"]
        response_type:
          "Bool"
application_settings:
  questions_by_indication:
    ileostomy:
      - "mobility"
      - "pain_calves"
      - "food_eat"
      - "drink_liquids"
      - "pain_change"
      - "urinating_regularly"
      - "bowel_movement"
      - "condition_change"

clinical_content:
  ileostomy:
    questions:
      mobility:
        text:
          ["Have you been able to walk around today?"]
        response_type:
          "Bool"
      pain_calves:
        text:
          ["Are you experiencing any pain or swelling in your cavles"]
        response_type:
          "Bool"
      food_eat:
        text:
          ["Have you been able to eat any meals?"]
        response_type:
          "Bool"
      drink_liquids:
        text:
          ["Have you been drinking liquids?"]
        response_type:
          "Bool"
      pain_change:
        text:
          ["Is your pain increased since yesterday?"]
        response_type:
          "Bool"
      urinating_regularly:
        text:
          ["Are you urinating regularly?"]
        response_type:
          "Bool"
      bowel_movement:
        text:
          ["Were you able to have a bowel movement today?"]
        response_type:
          "Bool"
      condition_change:
        text:
          ["Overall, do you feel better, worse or about the same as you did yesterday?"]
        response_type:
          "Bool"
    order_list:
      - "mobility"
      - "pain_calves"
      - "food_eat"
      - "drink_liquids"
      - "pain_change"
      - "urinating_regularly"
      - "bowel_movement"
      - "condition_change"
