application_text:
  introduction_text:
    welcome_text:
      "Welcome to the discharge monitoring application. We're going to ask some
      personal questions. Is now a good time?"
    user_identification:
      "I wanted to confirm that this was Tom. Is this correct?"
    failed_user_confirmation:
      "Hmm... something went wrong."
    exit_message:
      "Thank you for your input Tom. We'll be sending this information to your surgeon,
      who will follow-up with you if any additional information is required or if he needs
      to see you sooner than your scheduled appointment."
  questions:
      mobility:
        ["Have you been able to walk around today?"]
      pain_calves:
        ["Are you expierencing any pain or swelling in your cavles"]
      food_eat:
        ["Have you been able to eat any meals?"]
      drink_liquids:
        ["Have you been drinking liquids?"]
      pain_change:
        ["Is your pain decreased, increased, or about the same as it was yesterday?"]
      urinating_regularly:
        ["Are you urinating regularly?"]
      bowel_movement:
        ["Were you able to have  a bowel movement today?"]
      condition_change:
        ["Overall, do you feel better, worse or about the same as you did yesterday?"]
application_settings:
  hard_assertion_questions:
    - "person_confirmation"
  question_lists:
    "ILEOSTOMY":
      - "mobility"
      - "pain_calves"
      - "food_eat"
      - "drink_liquids"
      - "pain_change"
      - "urinating_regularly"
      - "bowel_movement"
      - "condition_change"
