application_text:
  introduction_text:
    welcome_text:
      "Welcome to the discharge monitering application. We're going
      to ask some private questions. Is it okay to proceed?"
    user_identification:
      "I wanted to confirm if this was Kevin, or a care taker
      for Kevin."

  question_text:
    # defined questions
    person_confirmation:
      care_taker:
        ["Alright, can we confirm the person we're monitering today? I current
        see that we're going over Kevin. Is this correct?"]
      patient:
        ["Hope you're feeling alright. I wanted to start by verifying this is
        the correct person... I see that you're Kevin, correct?"]
    moving_question:
      care_taker:
        ["Has Kevin been able to move around today?"]
      pateint:
        ["Have you been able to get up much today?"]
    eating_question:
      care_taker:
        ["Has Kevin been able to eat any food today?"]
      pateint:
        ["Have you been able to keep down food much today?"]
    drinking_question:
      care_taker:
        ["Has Kevin drank any fluids today?"]
      patient:
        ["Have you been able to drink any fluids today?"]
    pain_control_question:
      care_taker:
        ["Is Kevin in much pain today?"]
      patient:
        ["Have you had much pain today?"]
    medication_question:
      care_taker:
        ["Has Kevin been taking his pain medication?"]
      pateint:
        ["Have you been taking all of your pain medications?"]
    urination_question:
      care_taker:
        ["Has Kevin been able to urinate?"]
      patient:
        ["Have you been urinating regularly?"]
    urine_color_question:
      care_taker:
        ["What is the color of the urine?"]
      patient:
        ["What is the color of your urine?"]
    status_question:
      care_taker:
        ["Is Kevin feeling any better than yesterday?"]
      patient:
        ["Are you feeling better than yesterday?"]
    end_statement:
      care_taker:
        ["Thank you for your input on the care for Kevin. We'll be sending this
        information to his surgeon."]
      patient:
        ["Alright, thanks! I will send a note to your surgeon and we'll contact
        you if we need any more information."]
application_settings:
  master_questerion_ordering:
  - "person_confirmation"
  - "moving_question"
  - "eating_question"
  - "drinking_question"
  - "pain_control_question"
  - "medication_question"
  - "urination_question"
  - "urine_color_question"
  - "status_question"
  - "end_statement"
